// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: image.proto
#ifndef GRPC_image_2eproto__INCLUDED
#define GRPC_image_2eproto__INCLUDED

#include "image.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace ImageProto {

class ImageLogging final {
 public:
  static constexpr char const* service_full_name() {
    return "ImageProto.ImageLogging";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AskImage(::grpc::ClientContext* context, const ::ImageProto::ImageRequest& request, ::ImageProto::ImageResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ImageProto::ImageResponse>> AsyncAskImage(::grpc::ClientContext* context, const ::ImageProto::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ImageProto::ImageResponse>>(AsyncAskImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ImageProto::ImageResponse>> PrepareAsyncAskImage(::grpc::ClientContext* context, const ::ImageProto::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ImageProto::ImageResponse>>(PrepareAsyncAskImageRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void AskImage(::grpc::ClientContext* context, const ::ImageProto::ImageRequest* request, ::ImageProto::ImageResponse* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ImageProto::ImageResponse>* AsyncAskImageRaw(::grpc::ClientContext* context, const ::ImageProto::ImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ImageProto::ImageResponse>* PrepareAsyncAskImageRaw(::grpc::ClientContext* context, const ::ImageProto::ImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status AskImage(::grpc::ClientContext* context, const ::ImageProto::ImageRequest& request, ::ImageProto::ImageResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ImageProto::ImageResponse>> AsyncAskImage(::grpc::ClientContext* context, const ::ImageProto::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ImageProto::ImageResponse>>(AsyncAskImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ImageProto::ImageResponse>> PrepareAsyncAskImage(::grpc::ClientContext* context, const ::ImageProto::ImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ImageProto::ImageResponse>>(PrepareAsyncAskImageRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void AskImage(::grpc::ClientContext* context, const ::ImageProto::ImageRequest* request, ::ImageProto::ImageResponse* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ImageProto::ImageResponse>* AsyncAskImageRaw(::grpc::ClientContext* context, const ::ImageProto::ImageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ImageProto::ImageResponse>* PrepareAsyncAskImageRaw(::grpc::ClientContext* context, const ::ImageProto::ImageRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AskImage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AskImage(::grpc::ServerContext* context, const ::ImageProto::ImageRequest* request, ::ImageProto::ImageResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AskImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_AskImage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AskImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskImage(::grpc::ServerContext* context, const ::ImageProto::ImageRequest* request, ::ImageProto::ImageResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAskImage(::grpc::ServerContext* context, ::ImageProto::ImageRequest* request, ::grpc::ServerAsyncResponseWriter< ::ImageProto::ImageResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AskImage<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_AskImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_AskImage() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::ImageProto::ImageRequest, ::ImageProto::ImageResponse>(
          [this](::grpc::ServerContext* context,
                 const ::ImageProto::ImageRequest* request,
                 ::ImageProto::ImageResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->AskImage(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_AskImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskImage(::grpc::ServerContext* context, const ::ImageProto::ImageRequest* request, ::ImageProto::ImageResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void AskImage(::grpc::ServerContext* context, const ::ImageProto::ImageRequest* request, ::ImageProto::ImageResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_AskImage<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AskImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_AskImage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AskImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskImage(::grpc::ServerContext* context, const ::ImageProto::ImageRequest* request, ::ImageProto::ImageResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AskImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_AskImage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AskImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskImage(::grpc::ServerContext* context, const ::ImageProto::ImageRequest* request, ::ImageProto::ImageResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAskImage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_AskImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_AskImage() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->AskImage(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_AskImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AskImage(::grpc::ServerContext* context, const ::ImageProto::ImageRequest* request, ::ImageProto::ImageResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void AskImage(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AskImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_AskImage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::ImageProto::ImageRequest, ::ImageProto::ImageResponse>(std::bind(&WithStreamedUnaryMethod_AskImage<BaseClass>::StreamedAskImage, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_AskImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AskImage(::grpc::ServerContext* context, const ::ImageProto::ImageRequest* request, ::ImageProto::ImageResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAskImage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ImageProto::ImageRequest,::ImageProto::ImageResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AskImage<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AskImage<Service > StreamedService;
};

}  // namespace ImageProto


#endif  // GRPC_image_2eproto__INCLUDED
